### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by LidiaIvanova** [Xoxotynn/SwiftUICalculator#1]
Мне нравится структура проекта и аккуратность кода. Но приложение странно выглядит на очень больших и очень маленьких экранах (либо много свободного места, либо элементы не влезают). Так же нужно запретить поворот экрана.
Элементы должны растягиваться по размеру экрана, допустимо, что кнопки станут прямоугольными.
Паттерн Состояние в калькуляторе - это сильно)))

С цветами в приложении будет работать удобнее, если их оформить как расширение класса Color. 

Больше проблем каких-то не вижу, все вполне корректно.

**Comment by Xoxotynn** [comment]
Пофикшено
-Кнопки растягиваются по высоте экрана
-Цвета перемещены в расширение Color
-Запрещено поворачивать экран
